### PR TITLE
[enh] Add PCRE regex support

### PR DESCRIPTION
**Pull request by zamentur**
As the original branch of this https://github.com/YunoHost/SSOwat/pull/44 is missing, I have create a new one.

## The problem
Lua pattern are not well known and a lot of packager don't know how write this kind of regex. PCRE seems more familiar.

## Solution
Add support of PCRE, and keep support of lua pattern during a transition period.

## PR Status
Tested with nextcloud

## How to test
./ynh-dev use-git ssowat
setup one of this app and check it works as expected in their install script:
- kodi, 
- nextcloud (feature using /%.well%-known/)
- lutim as private
- lstu as private
- bozon as private,
- jirafeau
- lufi
## Validation

- [ ] Principle agreement 0/2 : 
- [ ] Quick review 0/1 : 
- [ ] Simple test 0/1 : 
- [ ] Deep review 0/1 :

### CODE REVIEW

**Comment by Psycojoker** [comment]
I would be interested in having the feedback from the apps team as they are the first concerned, therefor pinging them cc @frju365 @JimboJoe @Josue-T @maniackcrudelis (or at the one I know to be actives)

**Comment by Josue-T** [comment]
I had implemented the lua pattern in gogs and I confirm that it' a pain to use it. So I think that it's a really good idea to use PCRE instead.

**Comment by Psycojoker** [comment]
@maniackcrudelis said on the chat that this was a good idea too and that it has already been discussed in the past apparently.

I'm personally a bit weirded out by this dual match approach, I hope this won't create weird bugs :/ Maybe we should have something like explicitely specifying the regex type? Like starting the regex string with "pcre:" and "luare:" (default)?

Otherwise, LGTM.

**Review by JimboJoe — APPROVED** [review]
This is very LGTM as well! :+1:

**Comment by alexAubin** [comment]
Bumpitybump : what's the status of this ? Has it been tested ? Should it be merged ?

**Comment by zamentur** [comment]
I suggest to put it in a testing release

**Comment by alexAubin** [comment]
>Add support of PCRE, and keep support of lua pattern during a transition period.

Would there be a "simple" way to detect if the user is using Lua regexed or PCRE regexes ? So far it essentially looks like this will support both - but if we really want to push the usage to PCRE, we shall warn packagers about Lua regexes being deprecated somehow ?

This doesn't prevent from merging this though (I would be happy to merge this right away and include this in 3.3 testing)

**Comment by alexAubin** [comment]
Discussing this with ljf today : there are not so many apps using those regexes in fact (c.f. list in original post) so it's not so important to check. But ljf will investigate a bit more the question of identifying lua regexes

**Comment by alexAubin** [comment]
>But ljf will investigate a bit more the question of identifying lua regexes

Bump @zamentur ;)

(Otherwise we can also to just yolomerge this as it is, i dunno...)

**Comment by zamentur** [comment]
Tested with the %.well%-known/acme%-challenge ssowat rules

**Comment by zamentur** [comment]
I have found an error

**Pull request merged**
