### PR TITLE
Agentcobra skin patch

### PR DESCRIPTION
**Pull request by agentcobra**
add skin support

### CODE REVIEW

**Comment by agentcobra** [comment]
It's running on my ynh (https://agentcobra.net)

**Comment by zamentur** [comment]
Thanks for your contribution !
The idea is pretty cool !
Your pull request will be reviewed by several developers before to be intregrated.

I think the "brique" image license isn't compatible to be packaged with ssowat (AGPLv3). So we should change it.

About the code, some files (like translation) seems unchanged, it could be convenient to find a way to avoid to duplicate this kind of files.

**Comment by Psycojoker** [comment]
Small css bug, you need to add:

```css
html {
    width: 100%;
    height: 100%;
}
```

To your css file for the "background: cover" to streach itself on big screens.

**Comment by opi** [comment]
My point of view on this PR is that the "brique theme" must be separated from the "make ssowat themeable" code. The internetcube project should take care of its theme apart from SSOwat.  

I think we should close this PR, and work on a proper way to handle SSOwat skin (or theme).

- [ ] Move locales to avoid duplicates
- [ ] Handle mustache files https://github.com/YunoHost/SSOwat/blob/unstable/helpers.lua#L425-L437
- [ ] Decide if we wan't full theme override, or only CSS (+img) skin
- [ ] Allow theme (or skin) to be in any absolute path on the server ?

( don't think that I don't like your PR, I thank you to bootstrap this long-wanted feature ! )

**Comment by julienmalik** [comment]
Would shipping ssowat theme/skin as standard yunohost apps make sense ?

**Comment by agentcobra** [comment]
>  - [ ]  Allow theme (or skin) to be in any absolute path on the server ?
- [ ] Add a gallery with easy way to download skin ?

**Comment by Psycojoker** [comment]
Introducing theme support would be indeed very interesting, but that's another level of work.

**Comment by a1ex4** [comment]
You also need to take into account the [path to locales here in init.lua](https://github.com/YunoHost/SSOwat/blob/unstable/init.lua#L39).

**Comment by agentcobra** [comment]
I can (for the moment) use the locales from portal folder and later reorganize the ssowat folder's structure

**Comment by alexAubin** [comment]
[Semi-automatic message] 
Trying to clean PR which are opened and inactive since more than 6 months ~ 1 year ... I propose to close this PR and keep it in the "Horizon" milestone in case somebody wants to take care of it later. But in the meantime there's no point in keeping all of these opened if there's no indication that someone might work on this soon.

**Comment by agentcobra** [comment]
@alexAubin ok, no problem

**Pull request closed without merging**
