### PR TITLE
fix(Authorization): Skipped Autorization Header that are not Basic

### PR DESCRIPTION
**Pull request by titoko**

### CODE REVIEW

**Comment by nin0-0** [comment]
gives an error with codimd as seen in /var/log/nginx/<URI>-error.log

```bash
2020/12/12 09:11:07 [error] 12120#12120: *8 lua entry thread aborted: runtime error: error loading module 'helpers' from file '/usr/share/ssowat/helpers.lua':

**Comment by nin0-0** [comment]
edit the `:` to `then` in your if statement

**Comment by titoko** [comment]
Oups,I made this PR too quickly ;)!
Fixed

**Review by kay0u — APPROVED** [review]
Thank you for the fix.

Not tested yet (because I can't reproduce the original error), but looks great

**Comment by kay0u** [comment]
Should fix https://github.com/YunoHost/issues/issues/1689

**Comment by titoko** [comment]
Nice, what the next step then ? should I wait for another Approve before merge ?

**Review by alexAubin — APPROVED** [review]

**Comment by alexAubin** [comment]
Sounds good ! Thanks !

**Pull request merged**
