### PR TITLE
Fix a small error in the translations. 'Information' is always singular.

### PR DESCRIPTION
**Pull request by hnk**
Updated all neccessary files to reflect this change.

### CODE REVIEW

**Comment by Kloadut** [comment]
Nice catch !
Since you are updating the keyword `information`, you probably want to update the call as well (probably somewhere in the portal views)

**Comment by opi** [comment]
maybe not:

```
grep -Ri 'informations' .
./access.lua:         -- Edit user informations
./access.lua:                     flash("win", t("informations_updated"))
./portal/locales/fr.json:   "informations": "Vos informations",
./portal/locales/fr.json:   "informations_updated": "Informations mises à jour",
./portal/locales/fr.json:   "user_saving_fail": "Une erreur s'est produite lors de la modification des informations",
./portal/locales/en.json:   "informations": "Your informations",
./portal/locales/en.json:   "informations_updated": "Informations updated",
```

The keyword `informations` is not used now.

**Comment by hnk** [comment]
Yeah, I was searching for it as well and couldn't find it.

**Comment by opi** [comment]
Now that german language have been added (https://github.com/Kloadut/SSOwat/pull/14 & 92fdca3a3dd1286f63bf59f4c735d4b2180ff6cc) we need to change de.json file as weel.

**Comment by hnk** [comment]
Done.

**Comment by opi** [comment]
Done in 8eba1864a6df4edb49148660620fca540d5fc672  (can't be merged automatically, but I preserved authorship).
Thanks again.

**Pull request closed without merging**
