### PR TITLE
[enh] uses caching for hash to avoid heavy recalculation and process spawning

### PR DESCRIPTION
**Pull request by Psycojoker**
@sidddy can you tell me if this PR improve perfs on your side? It should be way faster now.

### CODE REVIEW

**Review by opi — COMMENTED** [review]
seems fair. need to test though

**Comment by sidddy** [comment]
I did a little performance test for loading a random application (shellinabox) from my raspi (from a remote location, so the response times will have some fluctuation, but anyway the conclusion is obvious... ;-) )

- via Basic Auth (no SSOWat involved): 741ms
- via SSOWat using old MD5 hash: 765ms
- via SSOWat using SHA512: 1006ms
- via SSOWat using cached SHA512: 747ms

Especially for shellinabox, roundtriptimes are crucial. In my setup, the RTT is around 50ms for basic auth, md5 and cached sha512. Using un-cached sha512, the RTT is around 130ms, which gives a really bad experience for shellinabox.

So, conclusion: I like the new sha512 cache :-)

**Review by opi — APPROVED** [review]
thanks

**Comment by Psycojoker** [comment]
Thanks a lot for your testing sidddy <3

**Pull request merged**
