### PR TITLE
provide more details about apps to template

### PR DESCRIPTION
**Pull request by gkrnours**
#58 got deleted by accident while trying to make it compatible with current unstable branch. So same content and ready to merge.

### CODE REVIEW

**Comment by julienmalik** [comment]
Thanks for the contribution. Looks good, but I want to test it. Anyway this should be reviewed by at least @opi

**Comment by julienmalik** [comment]
Didn't notice https://github.com/YunoHost/yunohost/pull/144 and https://dev.yunohost.org/issues/302 at the time I answered, sorry

**Comment by gkrnours** [comment]
A bit more than test might be required as the patch alter the format expected for conf.json without providing any fall back

**Comment by alexAubin** [comment]
I'm just randomly reading this PR and yunohost#144. In an attempt to revive this, is there anything needed to implement, apart from reviews/tests ? We should definitely be cautious with this, but it kinda looks like it's a relatively small, safe and legit change.

**Comment by alexAubin** [comment]
Random bump in case someone has a clue about this :s

**Comment by Psycojoker** [comment]
The idea was to modify sso template after that to display more information in it iirc, there was a screenshot somewhere but it looks like lost it because redmine sucks x(

**Comment by gkrnours** [comment]
Before merging, there is a decision to take on if we want to change the configuration format. 

That might not be the best choice.

Maybe it would be better to have a configuration being a list of app and a second file being the apps definition with all the details. That might provide a smoother experience when shipping the code and simplify internationalisation.

**Comment by alexAubin** [comment]
[Semi-automatic message] 
Trying to clean PR which are opened and inactive since more than 6 months ~ 1 year ... I propose to close this PR and keep it in the "Horizon" milestone in case somebody wants to take care of it later. But in the meantime there's no point in keeping all of these opened if there's no indication that someone might work on this soon.

**Pull request closed without merging**
