### PR TITLE
Fix refresh on touchmove

### PR DESCRIPTION
**Pull request by nicofrand**

### CODE REVIEW

**Comment by alexAubin** [comment]
Anybody has feedback on this ? This could be included in 3.2

**Comment by Psycojoker** [comment]
That would be nice. Last time I remember having a conversation with @nicofrand on #yunohsot stating that there was something missing to this PR, I don't remember if he added it :/

**Comment by nicofrand** [comment]
That PR is what was missing :). The previous one fixed a bug, this one fixes a new issue with the last Chrome versions where the touch events listeners behaviours changed.


Le 11 sept. 2018 04:27, Bram <notifications@github.com> a écrit :

That would be nice. Last time I remember having a conversation with @nicofrand on #yunohsot stating that there was something missing to this PR, I don't remember if he added it :/

**Comment by Psycojoker** [comment]
Ah perfect, thx :)

**Pull request merged**
